# Generated by Django 4.2.6 on 2023-10-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_alter_course_color_submission_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('P', 'Purple'), ('W', 'White')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('O', 'Orange'), ('P', 'Purple'), ('W', 'White')], default='W', max_length=2),
        ),
    ]
